import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: [
    "./src/db/schema/account-deletion-requests.ts",
    "./src/db/schema/account-export-requests.ts",
    "./src/db/schema/admin-audit.ts",
    "./src/db/schema/admin-users.ts",
    "./src/db/schema/affiliate.ts",
    "./src/db/schema/affiliate-fraud.ts",
    "./src/db/schema/coupon-codes.ts",
    "./src/db/schema/credit-auto-topup.ts",
    "./src/db/schema/credit-auto-topup-settings.ts",
    "./src/db/schema/credits.ts",
    "./src/db/schema/dividend-distributions.ts",
    "./src/db/schema/email-notifications.ts",
    "./src/db/schema/meter-events.ts",
    "./src/db/schema/notification-preferences.ts",
    "./src/db/schema/notification-queue.ts",
    "./src/db/schema/org-memberships.ts",
    "./src/db/schema/organization-members.ts",
    "./src/db/schema/payram.ts",
    "./src/db/schema/platform-api-keys.ts",
    "./src/db/schema/promotion-redemptions.ts",
    "./src/db/schema/promotions.ts",
    "./src/db/schema/provider-credentials.ts",
    "./src/db/schema/rate-limit-entries.ts",
    "./src/db/schema/secret-audit-log.ts",
    "./src/db/schema/session-usage.ts",
    "./src/db/schema/spending-limits.ts",
    "./src/db/schema/tenant-addons.ts",
    "./src/db/schema/tenant-api-keys.ts",
    "./src/db/schema/tenant-capability-settings.ts",
    "./src/db/schema/tenant-customers.ts",
    "./src/db/schema/tenants.ts",
    "./src/db/schema/user-roles.ts",
    "./src/db/schema/webhook-seen-events.ts",
  ],
  out: "./drizzle/migrations",
  dialect: "postgresql",
});
